### ISSUE TITLE
makeFindMixin returns nothing, but the websocket does (upgraded to Feathers4)

### ISSUE THREAD

**Issue by mainstreetmark** [feathersjs-ecosystem/feathers-vuex#324]
### Steps to reproduce

I had a working `makeFindMixin`, but then upgraded to Feathers4.  Now, no data seems to make it to vue.

```vue
<template lang="pug">
	div
		| {{ devicelibrary }}
</template>

<script>
import { makeFindMixin } from 'feathers-vuex'

export default {
	name: 'DeviceMenu',
	mixins: [makeFindMixin({ service: 'devicelibrary' })],
	computed: {
		devicelibraryParams() {
			return { query: { $sort: { device: 1 } } }
		}
	}
}
</script>
```

### Expected behavior
It should populate with results from the socket

### Actual behavior
`[]`

So, per [this note](https://feathers-vuex.feathers-plus.com/mixins.html#debugging-the-makefindmixin), i put a breakpoint.

* `serviceState.keyedById` is empty (well, an observer), 
* `queryInfo`:  {"qid":"default","query":{"$sort":{"device":1}},"queryId":"{\"$sort\":{\"device\":1}}","queryParams":{"$sort":{"device":1}}}"
* `params`:  {"query":{"$sort":{"device":1}},"qid":"default"}

Again, using a feathers hook, i see that the appropriate data has arrived.  The results are what I expect, given the query.  I do not mess with the params anywhere, eitherr.

**Comment by marshallswain** [comment]
Usually data not making it into the store means that there's either no `id` or `_id` OR the `idField` is misconfigured.  What is the idField of the data you're receiving?

**Comment by mainstreetmark** [comment]
It's `_id`, as it's a mongo backend.  Here's `data` from the `setupInstance`

```json
"{"_id":"5c9f8461007dff6e1b6295db","device":"Breaker","protocol":"modbus","connection":{},"polling_rate":1600,"data_rate":300,"address_offset":0,"image_url":null,"alarm_arm":"5aa7f8f2292e75045eb88fa4","primary_symbol":"KW","running_symbol":"KW","tag_library":[],"notes":"","manual":"","blocks":[{"address":"400001","length":34,"polling_rate":3}]}"
```

I even have `idField` configured in the feathers client setup, thusly (perhaps from an example?):

```vue
// Setup feathers-vuex
const { makeServicePlugin, makeAuthPlugin, BaseModel, models, clients, FeathersVuex } = feathersVuex(feathersClient, {
	serverAlias: 'api', // or whatever that makes sense for your project
	idField: '_id' // `id` and `_id` are both supported, so this is only necessary if you're using something else.
})

```

**Comment by mainstreetmark** [comment]
I'm walking through the process here.  In `getItemsFromQueryInfo`, and it seems I don't have a `pageId`.  Without a `pageId`, I don't get a `queryLevel`, and without that, I don't get a `pageLevel`, and without that, I don't get `ids`.

So, maybe I need to set up pagination?  Is this a new requirement maybe?

**Comment by marshallswain** [comment]
Try passing `paginate: false` in the params:

```js
devicelibraryParams() {
    return { 
        query: { $sort: { device: 1 } },
        paginate: false
    }
}
```

**Comment by mainstreetmark** [comment]
That worked!

Did I hit a weird use case, or is this standard practice in 2.x?

**Comment by marshallswain** [comment]
I think I need to try out the mixin on a service without server-side pagination enabled.

**Comment by J3m5** [comment]
I had the same problem once, until I figured this out.
Maybe `paginate: false` should be the default...

**Comment by marshallswain** [comment]
@J3m5 That probably would be a good idea.  It would be a breaking change, so it will have to wait a bit, though.  I'll see if I can fix this in the meantime.

**Comment by JorgenVatle** [comment]
Ran into a similar issue just a bit ago; while I do have pagination enabled on both the server and client-side, which seems to work just fine. I run into this particular issue whenever I would modify the Hook context's `params.query` object to apply server-only data. Seems like FeathersVuex uses the resulting query as a pagination key. I can't imagine this is intentional behaviour? Perhaps using the query passed in `serviceParams` would be better for pagination keys?

![image](https://user-images.githubusercontent.com/4034561/68857828-5f59f180-06ec-11ea-8671-35a3925892c3.png)

![image](https://user-images.githubusercontent.com/4034561/68857892-844e6480-06ec-11ea-92f7-b08174f73646.png)

**Comment by marshallswain** [comment]
It will work properly if you modify a clone of the params to return in your hook.

This is documented, but probably difficult to find when you come from the standpoint of "hey no data's loading".  If you modify the params, you MUST clone first.  It wouldn't make sense to use the other params, because those aren't the ones getting sent to the server.  This issue only exists because objects are passed by reference and not value (which is really supportive for setting up relational data, but not for tracking params)

![Screen Shot 2019-11-14 at 11 11 24 AM](https://user-images.githubusercontent.com/128857/68884025-75a58480-06cf-11ea-8d08-a370246a74f8.jpg)

**Comment by marshallswain** [comment]
> Seems like FeathersVuex uses the resulting query as a pagination key. I can't imagine this is intentional behaviour?
This is definitely intentional.  It can't really work any other way.  There are two parts to a paginated query: 

1. The "page" params, which includes `$limit` and `$skip`
2. The query params, which includes everything except `$limit` and `$skip`.

This is just a gotcha because FeathersJS doesn't clone the params before passing them into the hook chain.

**Comment by JorgenVatle** [comment]
Aha, understood. Thanks so much for the detailed response! 🤗

**Comment by marshallswain** [comment]
In 3.0, which is coming within a few days, pagination will be turned off by default.  This means that queries and lists will be realtime by default.

**Comment by marshallswain** [comment]
`feathers-vuex@3.0` is out and includes this fix.  The upgrade will take about 5 minutes, max.  There's only one change that might not even affect you: https://vuex.feathersjs.com/3.0-major-release.html#a-single-breaking-change
