### ISSUE TITLE
Featherjs-client socket.io in Nuxt ssr mode

### ISSUE THREAD

**Issue by nvthuong1996** [feathersjs-ecosystem/feathers-vuex#341]
I use feather-client whith socket.io in nuxt ssr render.   

My ssr nuxt logic:
user request income => plugin check cookie => getToken=> authenticate feather-client

Issues
Every user request income nuxt server => nuxt server create socket.io to backend => connect socket.io don't close after nuxt render.  It is unstable

I try disconnect socket in nuxt hook. But nuxt hook run in global, not in standbox every request income user.

video Issues
https://youtu.be/1RsnOp05ARI
your project
https://github.com/nvthuong1996/front-end

I'm not good at English. If I use the word incorrectly I'm sorry

**Comment by marshallswain** [comment]
My recommendation is to use feathers-rest on the Nuxt server.  I've never been able to get a socketio connection reliably working in any SSR framework.  This is also the only scenario where I recommend using a hybrid approach on the client.  If you configure feathers-rest on the client, then listen to socket events separately (since feathers-client doesn't support two simultaneous transports), you'll probably have an easier time getting things working and a more reliable setup.

**Comment by marshallswain** [comment]
I'm closing this now that we have a full Nuxt example in the docs.  Thanks!
