### ISSUE TITLE
Logout problem since migration to v2

### ISSUE THREAD

**Issue by klaus1978** [feathersjs-ecosystem/feathers-vuex#342]
### Behavior

Since my migration to the new version v2 I have following behavior when I try to logout:
I have a button which triggers my logout:
 

> this.$store.dispatch("auth/logout")

This throws an error:
index.js?cd73:240 Uncaught (in promise) Error: app.channel needs at least one channel name
    at Function.channel (...feathers/server/node_modules/@feathersjs/transport-commons/lib/channels/mixins.js:24)

If I check the status in Vue DEV TOOLS the last status is:
auth/setLogoutPending

If I now press my logout button again, it logs out and everything seems to work as expected...

Best regards Klaus

**Comment by J3m5** [comment]
This error seems to be related to feathers on the server side, the feathers-vuex [logout action](https://github.com/feathersjs-ecosystem/feathers-vuex/blob/78a5b2ed48c6d4885ba49711bd363860da61a4f0/src/auth-module/auth-module.actions.ts#L77) does nothing more than setting the logout pending state, calling the feather logout function and [cleaning the auth state](https://github.com/feathersjs-ecosystem/feathers-vuex/blob/78a5b2ed48c6d4885ba49711bd363860da61a4f0/src/auth-module/auth-module.mutations.ts#L46).

Which version of feathers and feathers-client are you using?

**Comment by klaus1978** [comment]
Hey,
thanks for your reply. 

On Server and Client side: v 4.3.10

thanks a lot
Klaus

**Comment by marshallswain** [comment]
This is definitely a problem with your server setup.  It seems you have an issue with your channel configuration.  You'll probably be able to track it fairly easily by setting a break point at the referenced line that's throwing the error:

> index.js?cd73:240 Uncaught (in promise) Error: app.channel needs at least one channel name
at Function.channel (...feathers/server/node_modules/@feathersjs/transport-commons/lib/channels/mixins.js:24)

You can use Visual Studio Code to start the FeathersJS server and set break points directly in the gutter.  Here's an example configuration:

```json
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Mocha Tests",
      "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
      "args": [
        "-u",
        "tdd",
        "--timeout",
        "999999",
        "--colors",
        "--exit",
        "${workspaceRoot}/{test,src}/**/*.test.js"
      ],
      "internalConsoleOptions": "openOnSessionStart",
      "env": {
        "NODE_ENV": "test"
      }
    },
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Development",
      "program": "${workspaceFolder}/src/index.js",
      "env": {
        "NODE_ENV": "development"
      }
    },
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Production",
      "program": "${workspaceFolder}/src/index.js",
      "env": {
        "NODE_ENV": "production"
      }
    },
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program w/ Seed Data",
      "program": "${workspaceFolder}/src/index.js",
      "args": [
        "--seed"
      ],
      "env": {
        "NODE_ENV": "development"
      }
    }
  ]
}
```

You can use the `Development` script, above, in your local environment.

To set the first break point, it's sometimes easiest to start the server, then check the "All Exceptions" checkbox at the bottom of the debugger sidebar, which is currently unchecked in this screenshot:

![Screen Shot 2019-11-09 at 1 20 02 PM](https://user-images.githubusercontent.com/128857/68534613-a6fb0a80-02f3-11ea-83d8-528084fb5132.jpg)

If you start or restart the server with that box checked, you'll hit a bunch of caught errors, so make sure you uncheck the box to prevent wasting your time ;).  With the server running, check that box then try logging out of your client, again.  The break point will hit and you'll be able to use the CALL STACK section of the debugger to trace the problem back to the actual source in your app.

Once you resolve the server issue, the response will return properly to the client and then Feathers-Vuex will resume its normal operation. 

I'm closing this issue since it's outside of the Feathers-Vuex scope.

Thanks @J3m5 for your input!
