### ISSUE TITLE
Is it possible to query the API and not update the vuex store?

### ISSUE THREAD

**Issue by juancampuzano** [feathersjs-ecosystem/feathers-vuex#460]
### Sample information

**Table Processes** 
>    Name: String
>    Status: Number

**Status enums**

>    0: stop
>    1: running
>    2: finish

I am making an API query using `limit 0` to get the total data according to my query. 
I get the total data that is in the stopped, running or finished state.

My problem is the following: reactivity is based on the **Processes table** and every time there is a change in this table I call the API again to know the total number of processes for each state. However, I am generating an infinitive loop because every time I call the API the store is also updated.

Is it possible to query the API and not update the vuex store?

**Comment by marshallswain** [comment]
Not currently, but this is something that is worth supporting.

**Comment by marshallswain** [comment]
I forget that there is a way to do this built into the feathers client.  Feathers-Vuex is built on top of the client and syncs up Vuex with the data received by the client, so you can just bypass feathers-vuex by doing this:

```js
import { feathersClient } from './feathers-client.js'

feathersClient.service('todos').find({ query: {} })
```

Since this option is available, I don't plan on adding a bypass for feathers-vuex.  The only downside I can think of is that the data is non-reactive, but there are some simple solutions for this once Vue 3 is released.
