### ISSUE TITLE
how do i get paramsForServer data

### ISSUE THREAD

**Issue by netwrkx** [feathersjs-ecosystem/feathers-vuex#484]
i cant seems to get data on the server, 

on Client Side
```
const servicePlugin = makeServicePlugin({
  Model: Address,
  service: feathersClient.service(servicePath),
  servicePath,
  paramsForServer: [{
    query: { dept: 'a' },
    populate: 'po-1',
    serialize: 'po-mgr',
    xQuery: 'dddddddd'
  }]
})
```
On server
```
const { paramsFromClient } = require('feathers-hooks-common')
  before: {
    all: [],
    find: [paramsFromClient('populate', 'serialize', 'query', 'xQuery'),  queryAddress()],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },
```

```
queryAddress file

context.params.query: {}
```

**Comment by hamiltoes** [comment]
[Here's the docs](https://vuex.feathersjs.com/service-plugin.html#configuration) about the service module config options.

> `paramsForServer` - Custom query operators that are ignored in the find getter, but will pass through to the server.

`paramsForServer` is a kinda misleading name because it's actually used here to strip properties out of the query you're passing to the `find()` *getter* which pulls data from the local store. (Maybe it should be called `serverOnlyQueryFields` or something). But basically this config options just allows you to pass the same query to the `find()` action and getter while telling the getter to ignore fields that are supported by your Feathers backend but are not standard query operators supported by Feathers Vuex's `find()` getter.

It looks like what you're actually trying to do is use `feathers-hooks-common`'s `paramsForServer` 
*hook* which is entirely separate (but unfortunately named the same) from the `paramsForServer` module config option in Feathers Vuex.

Your client side should look something like the following (untested)

```js
import { paramsForServer } from "feathers-hooks-common"

// .....

const servicePlugin = makeServicePlugin({
  Model: Address,
  service: feathersClient.service(servicePath),
  servicePath
})

// Add client-side hook `paramsForServer`
feathersClient.service(servicePath).hooks({
  before: {
    find: [(ctx /* FeathersJS hoook context */) => {
      ctx.params = paramsForServer(ctx.params, "populate", "serialize", "xQuery")
    }]
  }
});
```

Then in some component you will pass your `params` to the `find()` action.

```js
// someComponent.vue
fetchForeign() {
  // Call the Feathers Vuex `find()` action
  this.$q.$store.dispatch(`${servicePath}/find`, {
    query: { dept: 'a' },
    populate: 'po-1',
    serialize: 'po-mgr',
    xQuery: 'dddddddd')
  })
}
```

Then your server-side hook `paramsFromClient` will unpack the special params and stick them back in your server-side hook context.

**Comment by netwrkx** [comment]
@hamiltoes it worked, thanks
