### ISSUE TITLE
Error quering with $sort and $skip

### ISSUE THREAD

**Issue by koraniar** [feathersjs-ecosystem/feathers-vuex#486]
### Steps to reproduce
I am fetching all the data from the server by groups of 10 records ordered by a property called `status` with this recursive function:
```
async fetchDevicesFromApi(skipDevices) {
      const { Devices } = this.$FeathersVuex.API;

      const { total, data } = await Devices.find({
        query: {
          enabled: true,
          $sort: { status: -1 },
          $skip: skipDevices,
          $limit: 10,
        },
      });

      skipDevices += data.length;
      if (skipDevices < total) {
        await this.fetchDevicesFromApi(skipDevices);
      }
    },

fetchDevicesFromApi(0);
```

And I am printing the result in a table getting the data from the store with this computed function:
```
storedDevices() {
      const { Devices } = this.$FeathersVuex.API;

      const devices = Devices.findInStore({
        query: {
          enabled: true,
        },
      });
      return devices.data;
    },
```

But `storedDevices` only returns **53** records, `fetchDevicesFromApi` is fetching **56** records, and in my database, there are **56** records.

After some logs, I saw that **3** records fetched from the API were duplicated (Not in my DB).
I removed `$sort: { status: -1 }` from `fetchDevicesFromApi` and now there are no records duplicated and the `storedDevices` function returns the **56** records.

**55** of the **56** records have the `status` property value as `0` and the other record has this value as `2`, I think that like almost every record has the same `status`, they are not sorted the same in each time I fetch the records from the API, and that is why it returns records duplicated.

### Expected behavior
Get the same **56** records no matter the `$sort` value.

### Actual behavior
Fetch sorted records from API gets duplicated records.

### System configuration
**Module versions**:
- @feathersjs/feathers: 3.3.1
- feathers-vuex: 3.9.1

**NodeJS version**: v10.19.0

**Operating System**: OSX Catalina

**Browser Version**: Chrome Version 81.0.4044.138

**Vue Version**: 2.6.11

**Vue CLI**: v4

**Comment by hamiltoes** [comment]
This is likely not a Feathers Vuex issue because like you said, when you don't pass `$sort` to `Devices.find()`, you get all the records from the API and no duplicates. The call to `Devices.find()` just passes your params directly to the API so it seems like you're not actually pulling all 56 records to the client.

The first thing I would try is changing your `fetchDevicesFromApi` method to increment `skipDevices` by your page size (10) instead of `data.length` in case data.length != 10.

The second thing I would try is rewriting `fetchDevicesFromApi` to loop over pages instead of recurse.

What database are you using?

**Comment by koraniar** [comment]
Thank you for your fast response @hamiltoes 

Replacing `data.length` by `(this.page * 10)` has the same result

I have tried to perform the call to the API on change the page, but I get the same result.

I am using PosgreSQL.

**Comment by hamiltoes** [comment]
I think you're correct in your initial assessment.

According to the [Postgre docs](https://www.postgresql.org/docs/current/queries-order.html), sort order is not guaranteed amongst items with the same value. With 55 of your records having the same status, your query is not getting the same order every time. But you can specify multiple sorts so that items with the same value are then sorted.

This comment on [this stackoverflow question](https://stackoverflow.com/questions/11263715/is-postgresql-order-fully-guaranteed-if-sorting-on-a-non-unique-attribute) sums it up nicely:

>The only order that is guaranteed is the order that your "ORDER BY" imposes. If there are permutations possible within that order these could all be a valid output.

Try making your query sort by status *and* item ID. Then you'll get a stable status sort.

```js
      const { total, data } = await Devices.find({
        query: {
          enabled: true,
          $sort: {
            status: -1,
            id: 1 // use your service's ID field if it's not 'id'
          },
          $skip: skipDevices,
          $limit: 10,
        },
      });
```

**Comment by koraniar** [comment]
@hamiltoes You are completely right, excellent explanation.

Thank you so much.
