### ISSUE TITLE
Typo at FeathersVuexFind

### ISSUE THREAD

**Issue by shabanovd** [feathersjs-ecosystem/feathers-vuex#527]
https://github.com/feathersjs-ecosystem/feathers-vuex/blob/master/src/FeathersVuexFind.ts#L81

It should be check for `params`, not for `query`.

**Comment by J3m5** [comment]
I'm not even sure that it should check if params or query is truthy because we should be able to call the getter without them and return all the items.

**Comment by shabanovd** [comment]
@J3m5 good point

**Comment by fratzinger** [comment]
@shabanovd is right. Good catch! 
Before `feathers-vuex@3.12.0` `FeathersVuexFind` only worked with `:query="..."`. Now it also supports `:params="{}"`
This is a leftover from #521 .

@J3m5 I think the philosophy of `feathers-vuex` is to always provide at least an empty query to prevent accidentally complete requests. From time to time it annoys me but I think over all it's more helpful.

Should be fixed in #529

**Comment by J3m5** [comment]
Ok
 I don't know if it's already the case but it might be a good idea to specify this behavior in the docs because it deviate from the feathers client. 
Personally, by using the same API I would expect the same behavior.

**Comment by J3m5** [comment]
It appears that it has the same behavior than the makeFindMixin and the useFind hook.
It is consistent so it's not such a big deal.
I think that it should be left as is for now and ask what others think about it.
The only use case I see is if you want to explicitly not return the items but it can be achieved by passing $limit: 0.
Anyway, we'll see
