### ISSUE TITLE
Best practice for relation tables

### ISSUE THREAD

**Issue by PhipsSti** [feathersjs-ecosystem/feathers-vuex#540]
Hey guys, I am using using feathers-vuex for one of my projects and I am loving it so far. But at the moment I am having a bit of a struggle.

I have a table with things, a table with parts and a relating table between those two tables with an attribute amount.
The user should have an interface to edit products incl. the assignment of parts. The clone and commit pattern works perfect for the editing of the attributes of the product.
But adding and removing of the parts to products challenges me. At the moment my implementation sends changes automatically to the feathers-backend. Goal would be to keep all modification local until the user clicks on a save button.

What would be the easiest way to achieve this goal and handle these m:n-relations in an effective way?
(What I read so far it is not possible to delete relations locally and commit these changes after the click on the save-button. It is also tricky to distribute the save-event across multiple components.)

Thanks in advance!

**Comment by laurensiusadi** [comment]
Hi!

You'll have better luck by asking questions on the slack channel https://feathersjs.slack.com/ instead of a Github issue. I ask all sort of questions there.

**Comment by PhipsSti** [comment]
Thanks for the hint @laurensiusadi! Will also try it there.

**Comment by marshallswain** [comment]
@PhipsSti when you run `new Part(data)` what you get back is called a temporary record.  This means that it is stored on the client, but not yet on the server.  In order to show temporary records, you have to pass a `temps: true` into the params when performing a `Model.findInStore()`.  So you probably need to do two things to accomplish your objective:

1. Create a computed property that returns the results of `Model.findInStore({ query, temps: true }).data`.  Insert whichever query matches your data.  It will probably be something like `const query = { thingId: theThingId }`
2. Create a `saveAll` function that iterates through the computed array from #1 and calls `instance.save()` on each one.

The above might at least get you a step further.

**Comment by marshallswain** [comment]
Feel free to reopen if you have more you'd like to say.  Thanks, @laurensiusadi and @PhipsSti!
